services:
  asuka:
    build:
      context: .
      dockerfile: Dockerfile
      secrets:
        - discord_token
    image: asuka
    restart: unless-stopped
    user: asuka

secrets:
  discord_token:
    file: ./token.txt